### ISSUE TITLE
add the feature of turning on and off the dyno from the bot, please.

### ISSUE THREAD

**Issue by bulanbintang69** [AmineSoukara/Stream-HerokuLogs#2]
please sir

**Comment by AmineSoukara** [comment]
Okay, I'll Do It

**Comment by AmineSoukara** [comment]
![Screenshot_20220427-213516_Telegram](https://user-images.githubusercontent.com/65272894/165637722-a95e8a6b-5039-4196-b99c-a457b39e2a49.jpg)
✅️ Done

**Comment by AmineSoukara** [comment]
Redeploy ur app
